added files
GSS-Cogs/idpd-api-poc pull request #119
Opened 2023-11-08 10:29 UTC by rpm-data-dev

2023-11-08 13:44 UTC, mikeAdamss reviewed
Couple of comments but mainly things that haven't come out of the woodwork yet. Good job 😄 

One thing though - could do with the csv as well. If you look here: https://github.com/GSS-Cogs/idpd-api-poc/tree/main/src/store/csv/stub

the file structure follows the same dataset and edition identifiers I was talking about in the PR comments, so given its version 1 of the data, can you just add the csv as `./content/beis-2005-to-2019-local-authority-carbon-dioxide-co2-emissions/2005-2019/1.json` so the stub knows where to find it.

2023-11-08 13:44 UTC, mikeAdamss commented on src/store/metadata/stub/content/datasets.json
> +          "email": "Climatechange.Statistics@beis.gov.uk"
needs `mailto:` at the beginning. Our schemas arent _quite_ behaving as intended otherwise it would have told you.

2023-11-08 13:44 UTC, mikeAdamss commented on src/store/metadata/stub/content/editions/versions/beis_2005-2019_la_carbon_emission.json
> +{
same deal with file naming as the other one, literally the same name in fact, just at the /versions level.

2023-11-08 13:46 UTC, mikeAdamss commented on src/store/metadata/stub/content/editions/beis_2005-2019_la_carbon_emission.json
> +{
so we need to have very specific file naming for the stubbed code to work. always has to be

`<dataset_identifier>_<edition_identifier>.json`, so in this instance `beis-2005-to-2019-local-authority-carbon-dioxide-co2-emissions_2005-2019.json`

2023-11-10 08:23 UTC, mikeAdamss requested changes
RE topics, are are going to need them (otherwise we end up with broken links on the api, but you don't need to get into the weeds on parents and children unless you want to, as an example a topic of

```
            "@id": "https://staging.idpd.uk/topics/some-topic",
            "@type": "dcat:theme",
            "identifier": "some-topic",
            "title": "Some Topic",
            "description": "something describing some topic",
            "sub_topics": [],
            "parent_topics": []
        },
```

is completely viable for now, we can always get into parents/children as a separate piece later on.

2023-11-10 15:16 UTC, mikeAdamss commented
closing as amalgamated into this pr: https://github.com/GSS-Cogs/idpd-api-poc/pull/129

ty for this

2023-11-10 15:16 UTC, closed without merging

2023-11-14 09:58 UTC, rpm-data-dev commented
Hi Mike, I've tried adding in parent and subtopic into my new dataset (B3:
state of water environment)
```
        "sub_topics": [

        ],
        "parent_topics": [ "https://staging.idpd.uk/topics/climatechange"],
```
but python unit test is telling me to include topic field instead:
```
editions.0.topics
  Field required [type=missing, ***@***.***': 'https://staging....':
'Unit of Measure'}]}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing
```
I'll go ahead and change to topic for now but let me know where i'm going
wrong

On Fri, 10 Nov 2023 at 08:23, Michael Adams ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> RE topics, are are going to need them (otherwise we end up with broken
> links on the api, but you don't need to get into the weeds on parents and
> children unless you want to, as an example a topic of
>
>             ***@***.***": "https://staging.idpd.uk/topics/some-topic",
>             ***@***.***": "dcat:theme",
>             "identifier": "some-topic",
>             "title": "Some Topic",
>             "description": "something describing some topic",
>             "sub_topics": [],
>             "parent_topics": []
>         },
>
> is completely viable for now, we can always get into parents/children as a
> separate piece later on.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GSS-Cogs/idpd-api-poc/pull/119#pullrequestreview-1724253496>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQDAKPFD67UKRB6WCZILIGLYDXQBZAVCNFSM6AAAAAA7CUI5VSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMRUGI2TGNBZGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-11-14 10:31 UTC, rpm-data-dev commented
I've pushed it up, pull request is here:
https://github.com/GSS-Cogs/idpd-api-poc/pull/130

I resolved a conflict.

This isn't a nudge to get it merged just following up

On Tue, 14 Nov 2023 at 09:57, Richard Morgan ***@***.***>
wrote:

> Hi Mike, I've tried adding in parent and subtopic into my new dataset (B3:
> state of water environment)
> ```
>         "sub_topics": [
>
>         ],
>         "parent_topics": [ "https://staging.idpd.uk/topics/climatechange"
> ],
> ```
> but python unit test is telling me to include topic field instead:
> ```
> editions.0.topics
>   Field required [type=missing, ***@***.***': 'https://staging....':
> 'Unit of Measure'}]}}, input_type=dict]
>     For further information visit
> https://errors.pydantic.dev/2.4/v/missing
> ```
> I'll go ahead and change to topic for now but let me know where i'm going
> wrong
>
> On Fri, 10 Nov 2023 at 08:23, Michael Adams ***@***.***>
> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> RE topics, are are going to need them (otherwise we end up with broken
>> links on the api, but you don't need to get into the weeds on parents and
>> children unless you want to, as an example a topic of
>>
>>             ***@***.***": "https://staging.idpd.uk/topics/some-topic",
>>             ***@***.***": "dcat:theme",
>>             "identifier": "some-topic",
>>             "title": "Some Topic",
>>             "description": "something describing some topic",
>>             "sub_topics": [],
>>             "parent_topics": []
>>         },
>>
>> is completely viable for now, we can always get into parents/children as
>> a separate piece later on.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/GSS-Cogs/idpd-api-poc/pull/119#pullrequestreview-1724253496>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AQDAKPFD67UKRB6WCZILIGLYDXQBZAVCNFSM6AAAAAA7CUI5VSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMRUGI2TGNBZGY>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>